let oll_algo = [
    // {   'id': 'OLL01',
    //     'pattern': {'top': 'WWWW#WWWW', 'edge': '-#-/###/###/-#-'},
    // },
    {   'id': 'OLL02',
        'pattern': {'top': 'WWWW#WWWW', 'edge': '-##/###/-#-/-##'},
        'algo': [
            `F (R U R' U') F' Fw (R U R' U') Fw'`,
        ]
    },
    // {   'id': 'OLL03',
    //     'pattern': {'top': 'WWWW#W#WW', 'edge': '##-/-#-/##-/-##'},
    // },
    // {   'id': 'OLL04',
    //     'pattern': {'top': 'WWWW#WWW#', 'edge': '-##/##-/-#-/##-'},
    // },
    // {   'id': 'OLL05',
    //     'pattern': {'top': 'WWWW##W##', 'edge': '##-/-##/#--/---'},
    // },
    {   'id': 'OLL06',
        'pattern': {'top': 'W##W##WWW', 'edge': '---/##-/--#/##-'},
        'algo': [
            `Rw U2' R' U' R U' Rw'`,
        ]
    },
    // {   'id': 'OLL07',
    //     'pattern': {'top': 'W#W##W#WW', 'edge': '#--/---/##-/-##'},
    // },
    // {   'id': 'OLL08',
    //     'pattern': {'top': '#WW##WW#W', 'edge': '-##/---/-##/#--'},
    // },
    // {   'id': 'OLL09',
    //     'pattern': {'top': 'W#W##WWW#', 'edge': '--#/#--/-#-/##-'},
    // },
    // {   'id': 'OLL10',
    //     'pattern': {'top': 'WW###WW#W', 'edge': '##-/--#/-#-/--#'},
    // },
    // {   'id': 'OLL11',
    //     'pattern': {'top': 'WWWW####W', 'edge': '##-/-#-/#--/--#'},
    // },
    // {   'id': 'OLL12',
    //     'pattern': {'top': '##WW##WWW', 'edge': '--#/-#-/--#/##-'},
    // },
    // {   'id': 'OLL13',
    //     'pattern': {'top': 'WWW####WW', 'edge': '##-/---/#--/-##'},
    // },
    // {   'id': 'OLL14',
    //     'pattern': {'top': 'WWW###WW#', 'edge': '-##/#--/---/##-'},
    // },
    // {   'id': 'OLL15',
    //     'pattern': {'top': 'WWW###WW#', 'edge': '##-/--#/#--/-#-'},
    // },
    // {   'id': 'OLL16',
    //     'pattern': {'top': 'WWW####WW', 'edge': '-##/#--/--#/-#-'},
    // },
    // {   'id': 'OLL17',
    //     'pattern': {'top': '#WWW#WWW#', 'edge': '-##/-##/-#-/-#-'},
    // },
    // {   'id': 'OLL18',
    //     'pattern': {'top': 'WW#W#WWW#', 'edge': '-#-/###/-#-/-#-'},
    // },
    // {   'id': 'OLL19',
    //     'pattern': {'top': '#W#W#WWWW', 'edge': '-#-/-##/-##/-#-'},
    // },
    {   'id': 'OLL20',
        'pattern': {'top': '#W#W#W#W#', 'edge': '-#-/-#-/-#-/-#-'},
        'algo': [
            `(M' U')4 U2 (M' U')4`,
        ]
    },
    {   'id': 'OLL21',
        'pattern': {'top': 'W#W###W#W', 'edge': '#-#/---/---/#-#'},
        'algo': [
            `(R U2 R' U') (R U R' U' R U' R')`,
        ]
    },
    {   'id': 'OLL22',
        'pattern': {'top': 'W#W###W#W', 'edge': '--#/#-#/---/--#'},
        'algo': [
            `R U2' (R2' U') (R2 U') (R2' U2' R)`,
        ]
    },
    {   'id': 'OLL23',
        'pattern': {'top': '######W#W', 'edge': '---/---/---/#-#'},
        'algo': [
            `x' (R U R' U')2 D (U R U' R')2 D' [x]`,
        ]
    },
    {   'id': 'OLL24',
        'pattern': {'top': 'W#####W##', 'edge': '#--/---/---/#--'},
        'algo': [
            `(Rw U R' U') Rw' (F R F')`,
        ]
    },
    {   'id': 'OLL25',
        'pattern': {'top': '##W###W##', 'edge': '--#/--#/---/---'},
        'algo': [
            `Lw' U' L' U R U' L U [x']`,
        ]
    },
    // {   'id': 'OLL26',
    //     'pattern': {'top': 'W#####W#W', 'edge': '---/#--/--#/#--'},
    // },
    // {   'id': 'OLL27',
    //     'pattern': {'top': 'W#W#####W', 'edge': '#--/---/#--/--#'},
    // },
    {   'id': 'OLL28',
        'pattern': {'top': '#####W#W#', 'edge': '---/---/-#-/-#-'},
        'algo': [
            `(Rw U R' U') (Rw' R) (U R U' R')`,
        ]
    },
    // {   'id': 'OLL29',
    //     'pattern': {'top': 'W####WWW#', 'edge': '#--/---/-#-/##-'},
    // },
    // {   'id': 'OLL30',
    //     'pattern': {'top': 'W#W##W#W#', 'edge': '---/#--/##-/-#-'},
    // },
    // {   'id': 'OLL31',
    //     'pattern': {'top': '#WW##W##W', 'edge': '-##/---/-#-/--#'},
    // },
    // {   'id': 'OLL32',
    //     'pattern': {'top': 'WW#W##W##', 'edge': '##-/-#-/---/#--'},
    // },
    {   'id': 'OLL33',
        'pattern': {'top': 'WW####WW#', 'edge': '##-/---/---/##-'},
        'algo': [
            `(R U R' U') (R' F R F')`,
        ]
    },
    // {   'id': 'OLL34',
    //     'pattern': {'top': 'WWW####W#', 'edge': '-#-/#--/#--/-#-'},
    // },
    // {   'id': 'OLL35',
    //     'pattern': {'top': '#WWW##W##', 'edge': '-#-/-#-/#--/#--'},
    // },
    // {   'id': 'OLL36',
    //     'pattern': {'top': '#WW##WW##', 'edge': '-#-/---/##-/#--'},
    // },
    {   'id': 'OLL37',
        'pattern': {'top': '##W##WWW#', 'edge': '---/---/##-/##-'},
        'algo': [
            `F (R U' R' U') (R U R' F')`,
        ]
    },
    // {   'id': 'OLL38',
    //     'pattern': {'top': 'W####W#WW', 'edge': '#--/---/-##/-#-'},
    // },
    // {   'id': 'OLL39',
    //     'pattern': {'top': 'WW#####WW', 'edge': '##-/---/--#/-#-'},
    // },
    // {   'id': 'OLL40',
    //     'pattern': {'top': '#WW###WW#', 'edge': '-##/--#/---/-#-'},
    // },
    // {   'id': 'OLL41',
    //     'pattern': {'top': 'W#W##W#W#', 'edge': '#-#/---/-#-/-#-'},
    // },
    // {   'id': 'OLL42',
    //     'pattern': {'top': '#W###WW#W', 'edge': '-#-/---/-#-/#-#'},
    // },
    // {   'id': 'OLL43',
    //     'pattern': {'top': '#####WWWW', 'edge': '---/---/-#-/###'},
    // },
    // {   'id': 'OLL44',
    //     'pattern': {'top': 'WW#W##W##', 'edge': '-#-/###/---/---'},
    // },
    {   'id': 'OLL45',
        'pattern': {'top': 'WW####WW#', 'edge': '-#-/#-#/---/-#-'},
        'algo': [
            `F R U R' U' F'`,
        ]
    },
    // {   'id': 'OLL46',
    //     'pattern': {'top': '##WW#W##W', 'edge': '---/-#-/###/---'},
    // },
    // {   'id': 'OLL47',
    //     'pattern': {'top': 'W#WW##WWW', 'edge': '#--/-#-/#-#/##-'},
    // },
    {   'id': 'OLL48',
        'pattern': {'top': 'W#W##WWWW', 'edge': '--#/#-#/-#-/-##'},
        'algo': [
            `F (R U R' U')2 F'`,
        ]
    },
    // {   'id': 'OLL49',
    //     'pattern': {'top': 'WWW##WW#W', 'edge': '##-/---/###/#--'},
    // },
    // {   'id': 'OLL50',
    //     'pattern': {'top': 'WWWW##W#W', 'edge': '-##/###/---/--#'},
    // },
    // {   'id': 'OLL51',
    //     'pattern': {'top': 'WWW###WWW', 'edge': '-##/#-#/---/-##'},
    // },
    // {   'id': 'OLL52',
    //     'pattern': {'top': 'W#WW#WW#W', 'edge': '#--/-#-/###/#--'},
    // },
    // {   'id': 'OLL53',
    //     'pattern': {'top': 'WWW##WW#W', 'edge': '###/---/-#-/#-#'},
    // },
    // {   'id': 'OLL54',
    //     'pattern': {'top': 'W#W##WWWW', 'edge': '#-#/---/-#-/###'},
    // },
    // {   'id': 'OLL55',
    //     'pattern': {'top': 'W#WW#WW#W', 'edge': '---/###/###/---'},
    // },
    // {   'id': 'OLL56',
    //     'pattern': {'top': 'WWW###WWW', 'edge': '-#-/#-#/#-#/-#-'},
    // },
    {   'id': 'OLL57',
        'pattern': {'top': '#W#####W#', 'edge': '-#-/---/---/-#-'},
        'algo': [
            `(R U R' U') M' (U R U' Rw') `,
        ]
    },
    {   'id': 'OLL57',
        'pattern': {'top': 'YRYYYYYOY', 'edge': 'RYR/GGG/BBB/OYO'},
        'algo': [
            `(M' U' M' U' M' U2) (M U' M U' M U2)`,
        ]
    },
];


let pll_algo = [
    {   'id': 'PLL01',
        'name': 'U(b) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRR/GBG/BOB/OGO', 'arrows': ['6->8', '8->4', '4->6']},
        'algo': [
            `(R2 U R U) (R' U' R' U') (R' U' R')`,
        ]
    },
    {   'id': 'PLL02',
        'name': 'U(a) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRR/GOG/BGB/OBO', 'arrows': ['6->4', '4->8', '8->6']},
        'algo': [
            `F2 U' (L R' F2 L' R) U' F2`,
            `y' R2' U' (F B' R2 F' B) U' R2'`,
        ]
    },
    {   'id': 'PLL03',
        'name': 'A(b) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRO/GGO/GBR/BOB', 'arrows': ['3->7', '7->9', '9->3']},
        'algo': [
            `x' (R U' R) D2 (R' U R) D2 R2`,
        ]
    },
    {   'id': 'PLL04',
        'name': 'A(a) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRB/GGB/OBO/ROG', 'arrows': ['7->3', '9->7', '3->9']},
        'algo': [
            `x' R2 D2 (R' U' R) D2 (R' U R')`,
            `U2 (r U r' U') r' F r2 (U' r' U' r U r') F' //wide T-perm`
        ]
    },
    {   'id': 'PLL05',
        'name': 'Z perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RBR/GOG/BRB/OGO', 'arrows': ['2<->6', '4<->8']},
        'algo': [
            `(R' U' R U') (R U R U') (R' U R U) (R2 U' R') U2`,
            `(M2 U') (M2 U') (M' U2) (M2 U2) (M' U2)`,
        ]
    },
    {   'id': 'PLL06',
        'name': 'H perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'ROR/GBG/BGB/ORO', 'arrows': ['2<->8', '4<->6']},
        'algo': [
            `M2 U' M2 U2' M2 U' M2`,
            `(M2 U2 M2) U (M2 U2 M2) U'`
        ]
    },
    {   'id': 'PLL07',
        'name': 'E perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'BRG/RGO/RBO/BOG', 'arrows': ['1<->3', '7<->9']},
        'algo': [
            // https://www.youtube.com/watch?v=9UzbyvSpQRY
            `(R2 U F') (R' U R U')3 (F U' R2)`,
            `x' (R U' R' D) (R U R' D') (R U R' D) (R U' R' D') x`,
        ]
    },
    {   'id': 'PLL08',
        'name': 'T perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRB/GBG/OGR/OOB', 'arrows': ['4<->6', '3<->9']},
        'algo': [
            `(R U R' U') (R' F) (R2 U' R' U) (R U R') F'`,
        ]
    },
    {   'id': 'PLL09',
        'name': 'V perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'OBR/BGG/BRG/OOR', 'arrows': ['1<->9', '2<->6']},
        'algo': [
            // https://www.youtube.com/watch?v=XYzsUPqElTk
            `(R' U R' U') (R D' R' D) R' (U D') (R2 U' R2 D R2)`,
        ]
    },
    {   'id': 'PLL10',
        'name': 'F perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'ROB/GGG/OBR/ORB', 'arrows': ['2<->8', '3<->9']},
        'algo': [
            `(R' U' F') (T-perm skip final F) U R`,
        ]
    },
    {   'id': 'PLL12',
        'name': 'R perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RGB/GRG/OBR/OOB', 'arrows': ['2<->4', '3<->9']},
        'algo': [
            `(R U R' F') (R U2) (R' U2) (R' F R U) (R U2 R' U')`,
        ]
    },
    {   'id': 'PLL13',
        'name': 'J(b) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RRB/GGG/OOR/OBB', 'arrows': ['3<->9', '6<->8']},
        'algo': [
            `(R U2' R' U' R U2') (L' U R' U' L)`,
            `(R U R' F') (R U R' U') (R' F) (R2 U') R' U'`,
        ]
    },
    {   'id': 'PLL14',
        'name': 'J(a) perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'RBB/GGG/ORR/OOB', 'arrows': ['2<->6', '3<->9']},
        'algo': [
            `(x R2) (F R F') (R U2) (r' U r U2) x'`,
        ]
    },
    {   'id': 'PLL15',
        'name': 'Y perm',
        'pattern': {'top': 'YYYYYYYYY', 'edge': 'OGR/BRG/BBG/OOR', 'arrows': ['2<->4', '1<->9']},
        'algo': [
            `(R' U' R U') (J perm) (U R' U R)`,
            `F (R U' R' U') (R U R' F') (R U R' U') (R' F R F')`,
        ]
    },
    {   'name': 'Void parity',
        'pattern': {'top': 'YYYY#YYYY', 'edge': 'RBR/GGG/BRB/OOO', 'arrows': ['2<->6']},
        'algo': [
            `(M' U)2 (M' U')2 (M' 2U) (M' U')2`,
        ]
    },
];


let f2l_algo = [
    // image source: https://www.gcubing.com/algorithms/3x3/f2l/3x3-f2l.php
    // {   'id': 'F2L01',
    //     'pattern': {'top': '.....B..B', 'front': '..WBB.BB.', 'right': 'RR..RR.RR'},
    // },
    // {   'id': 'F2L02',
    //     'pattern': {'top': '.......RR', 'front': '.BBBB.BB.', 'right': 'W...RR.RR'},
    // },
    // {   'id': 'F2L03',
    //     'pattern': {'top': '.B......R', 'front': '..BBB.BB.', 'right': 'W...RR.RR'},
    // },
    // {   'id': 'F2L04',
    //     'pattern': {'top': '...R....B', 'front': '..WBB.BB.', 'right': 'R...RR.RR'},
    // },
    // {   'id': 'F2L05',
    //     'pattern': {'top': '.....B...', 'front': '...BB.BBW', 'right': '.R..RRBRR'},
    // },
    // {   'id': 'F2L06',
    //     'pattern': {'top': '.......R.', 'front': '.B.BB.BBR', 'right': '....RRWRR'},
    // },
    {   'id': 'F2L07',
        'pattern': {'top': '.....B...', 'front': '...BB.BBB', 'right': '.R..RRRRR'},
        'algo': [
            `U' (R' F R F') (R U R')`,
        ]
    },
    // {   'id': 'F2L08',
    //     'pattern': {'top': '.......R.', 'front': '.B.BB.BBB', 'right': '....RRRRR'},
    // },
    // {   'id': 'F2L09',
    //     'pattern': {'top': '.B......B', 'front': '..WBB.BB.', 'right': 'R...RR.RR'},
    // },
    // {   'id': 'F2L10',
    //     'pattern': {'top': '...R....R', 'front': '..BBB.BB.', 'right': 'W...RR.RR'},
    // },
    // {   'id': 'F2L11',
    //     'pattern': {'top': '...B....B', 'front': '..WBB.BB.', 'right': 'R...RR.RR'},
    // },
    {   'id': 'F2L12',
        'pattern': {'top': '.R......R', 'front': '..BBB.BB.', 'right': 'W...RR.RR'},
        'algo': [
            `(R' F R F') U2 (R U R' U') (F R' F' R)`,
        ]
    },
    {   'id': 'F2L13',
        'pattern': {'top': '.......BB', 'front': '.RWBB.BB.', 'right': 'R...RR.RR'},
        'algo': [
            `(R U R') U2 (R U' R') U (R U' R')`,
        ]
    },
    {   'id': 'F2L14',
        'pattern': {'top': '.....R..R', 'front': '..BBB.BB.', 'right': 'WB..RR.RR'},
        'algo': [
            `U (F (R U R' U') F') (U R U' R')`,
        ]
    },
    // {   'id': 'F2L15',
    //     'pattern': {'top': '.R......B', 'front': '..WBB.BB.', 'right': 'R...RR.RR'},
    // },
    // {   'id': 'F2L16',
    //     'pattern': {'top': '...B....R', 'front': '..BBB.BB.', 'right': 'W...RR.RR'},
    // },
    // {   'id': 'F2L17',
    //     'pattern': {'top': '.....R..B', 'front': '..WBB.BB.', 'right': 'RB..RR.RR'},
    // },
    // {   'id': 'F2L18',
    //     'pattern': {'top': '.......BR', 'front': '.RBBB.BB.', 'right': 'W...RR.RR'},
    // },
    // {   'id': 'F2L19',
    //     'pattern': {'top': '.......RB', 'front': '.BWBB.BB.', 'right': 'R...RR.RR'},
    // },
    // {   'id': 'F2L20',
    //     'pattern': {'top': '.....B..R', 'front': '..BBB.BB.', 'right': 'WR..RR.RR'},
    // },
    // {   'id': 'F2L21',
    //     'pattern': {'top': '.....B..W', 'front': '..RBB.BB.', 'right': 'BR..RR.RR'},
    // },
    {   'id': 'F2L22',
        'pattern': {'top': '.......RW', 'front': '.BRBB.BB.', 'right': 'B...RR.RR'},
        'algo': [
            `(R' F R F') (R U' R' U R U' R')`,
        ]
    },
    // {   'id': 'F2L23',
    //     'pattern': {'top': '.B......W', 'front': '..RBB.BB.', 'right': 'B...RR.RR'},
    // },
    // {   'id': 'F2L24',
    //     'pattern': {'top': '...R....W', 'front': '..RBB.BB.', 'right': 'B...RR.RR'},
    // },
    // {   'id': 'F2L25',
    //     'pattern': {'top': '...B....W', 'front': '..RBB.BB.', 'right': 'B...RR.RR'},
    // },
    // {   'id': 'F2L26',
    //     'pattern': {'top': '.R......W', 'front': '..RBB.BB.', 'right': 'B...RR.RR'},
    // },
    // {   'id': 'F2L27',
    //     'pattern': {'top': '.......BW', 'front': '.RRBB.BB.', 'right': 'B...RR.RR'},
    // },
    // {   'id': 'F2L28',
    //     'pattern': {'top': '.....R..W', 'front': '..RBB.BB.', 'right': 'BB..RR.RR'},
    // },
    {   'id': 'F2L29',
        'pattern': {'top': '.......R.', 'front': '.B.BB.BBW', 'right': '....RRBRR'},
        'algo': [
            `(R' F R F') U (R U' R')`,
        ]
    },
    // {   'id': 'F2L30',
    //     'pattern': {'top': '.....B...', 'front': '...BB.BBR', 'right': '.R..RRWRR'},
    // },
    // {   'id': 'F2L31',
    //     'pattern': {'top': '........B', 'front': '..WBBBBB.', 'right': 'R..RRR.RR'},
    // },
    // {   'id': 'F2L32',
    //     'pattern': {'top': '........R', 'front': '..BBBBBB.', 'right': 'W..RRR.RR'},
    // },
    // {   'id': 'F2L33',
    //     'pattern': {'top': '........B', 'front': '..WBBRBB.', 'right': 'R..BRR.RR'},
    // },
    // {   'id': 'F2L34',
    //     'pattern': {'top': '........R', 'front': '..BBBRBB.', 'right': 'W..BRR.RR'},
    // },
    // {   'id': 'F2L35',
    //     'pattern': {'top': '........W', 'front': '..RBBRBB.', 'right': 'B..BRR.RR'},
    // },
    // {   'id': 'F2L36',
    //     'pattern': {'top': '........W', 'front': '..RBBBBB.', 'right': 'B..RRR.RR'},
    // },
    // {   'id': 'F2L37',
    //     'pattern': {'top': '.........', 'front': '...BBBBBW', 'right': '...RRRBRR'},
    // },
    // {   'id': 'F2L38',
    //     'pattern': {'top': '.........', 'front': '...BBBBBR', 'right': '...RRRWRR'},
    // },
    // {   'id': 'F2L39',
    //     'pattern': {'top': '.........', 'front': '...BBRBBW', 'right': '...BRRBRR'},
    // },
    // {   'id': 'F2L40',
    //     'pattern': {'top': '.........', 'front': '...BBRBBR', 'right': '...BRRWRR'},
    // },
    // {   'id': 'F2L41',
    //     'pattern': {'top': '.........', 'front': '...BBRBBB', 'right': '...BRRRRR'},
    // },
    {   'id': '4x4 OLL parity',
        'pattern': {'top': 'YYYYYYYYYYYYYOOY', 'edge': 'RRRR/GGGG/BBBB/OYYO'},
        'algo': [
            `(r' U2) (l F2 l' F2) r2 (U2 r U2 r' U2) F2 r2 F2`,
        ]
    },
    {   'name': '4x4 PLL parity',
        'pattern': {'top': 'YYYYYYYYYYYYYYYY', 'edge': 'ROOR/GGGG/BBBB/ORRO', 'arrows': ['2<->15', '3<->14']},
        'algo': [
            `r2 U2 r2 Uw2 r2 u2`,
        ]
    },
];


let four_by_four_algo = [
];


let algos = [
    oll_algo,
    pll_algo,
    f2l_algo,
];
